spring:
  application:
    name: rating-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties.hibernate:
      hbm2ddl.auto: validate
      show_sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog.master.yaml

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

server:
  port: ${APP_PORT:8090}