spring:
  application:
    name: auth-service

  kafka:
    bootstrap-servers: ${KAFKA_PRODUCER_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true

server:
  port: 8090
