spring:
  application:
    name: auth-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  liquibase:
    enabled: false

server:
  port: 8090
