spring:
  application:
    name: auth-service

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_CONSUMER_BOOTSTRAP_SERVERS}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: payment-subscription-events
      properties:
        spring.json.trusted.packages: "*"
        value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: ${KAFKA_PRODUCER_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

jwt:
  access:
    secret: ${JWT_SECRET:access_secret}
    lifetime: ${JWT_LIFETIME:60m}
  refresh:
    secret: ${JWT_SECRET:refresh_secret}
    lifetime: ${JWT_LIFETIME:4320m}

code.lifetime: 3

path:
  account-service: ${ACCOUNT_SERVICE:account-service}

server:
  port: ${APP_PORT:8090}
