spring:
  application:
    name: subscription-service

  datasource:
    url: ${DB_URL}
    username: {DB_USERNAME}
    password: {DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties.hibernate:
      hbm2ddl.auto: validate

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_PRODUCER_BOOTSTRAP_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerialization
      value-serializer: org.apache.kafka.common.serialization.JsonSerialization
      properties:
        enable.idempotence: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

server:
  port: ${APP_PORT:8090}
