spring:
  application:
    name: account-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  liquibase:
    enabled: false

server:
  port: 8090
