name: Backend CI

on:
  push:
    branches:
      - main
      - develop
      - bugfix/*
      - release/*
      - feature/*
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
      - develop
      - bugfix/*
      - release/*
      - feature/*
    paths:
      - 'backend/**'

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon
      - run: ./gradlew test
