name: Frontend CI

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: cd frontend && npm ci

      - name: 🚀 Preview build app
        run: cd frontend && eas init && eas update --auto --branch "${{ github.event.pull_request.head.ref }}" --non-interactive
        if: github.event.pull_request.base.ref == 'develop'

      - name: 🚀 Build app
        run: cd frontend && eas build --non-interactive
        if: github.event.pull_request.base.ref == 'main'
