name: Frontend CI

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.setup-node.outputs.node-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: cd frontend && npm ci

  preview:
    name: Preview build
    needs: setup
    if: github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Run preview build
        run: cd frontend && eas update --auto --branch "${{ github.event.pull_request.head.ref }}" --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  production:
    name: Production build
    needs: setup
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Run production build
        run: cd frontend && eas build --platform android --non-interactive --no-wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}